### ISSUE TITLE
Use only one bugtracker

### ISSUE THREAD

**Issue by ite-klass** [editorconfig/editorconfig-visualstudio#20]
I am very confused as to which issue tracker should be used; the one on this repository,
or the one on the editorconfig repository which has a vs-plugin label and is pointed to by the README in this repository.

If both had all tickets that maybe would have been less of a problem, but I see ticket comments pointing to the other tracker to an issue that is not in the other.

IIRC you can disable the issue tracker on repositories, so I would suggest dropping one for the other.
If need be, there is also a (manual) migration path for existing tickets (prepare JSON data for github stuff and send it to them).

As it currently is, its confusing, potentially redundant, more for to maintain, and harder to search.

**Comment by xuhdev** [comment]
We used to use one centralized bug tracker, but we made the switch recently editorconfig/editorconfig#207. The README file isn't up-to-date.
