### ISSUE TITLE
EditorConfigWrapper not found on VisualStudio 2015

### ISSUE THREAD

**Issue by felipeleusin** [editorconfig/editorconfig-visualstudio#26]
After opening a project without a .editorconfig file i'm getting an error from VisualStudio, after checking the ActivityLog.xml file I found the following error:

<entry>
    <record>662</record>
    <time>2015/08/26 14:28:33.116</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.IO.FileNotFoundException: Could not load file or assembly &apos;EditorConfigWrapper.dll&apos; or one of its dependencies. The specified module could not be found.&#x000D;&#x000A;File name: &apos;EditorConfigWrapper.dll&apos;&#x000D;&#x000A;   at EditorConfig.VisualStudio.Plugin.LoadSettings(String path)&#x000D;&#x000A;   at EditorConfig.VisualStudio.Plugin..ctor(IWpfTextView view, ITextDocument document, DTE dte, ErrorListProvider messageList, IViewSettingsContainer viewSettingsContainer)&#x000D;&#x000A;   at EditorConfig.VisualStudio.PluginFactory.TextViewCreated(IWpfTextView view)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.&lt;&gt;c__DisplayClass241_0.&lt;BindContentTypeSpecificAssets&gt;b__1()&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)&#x000D;&#x000A;&#x000D;&#x000A;</description>
  </entry>

Have tried removing and reinstalling the addon and the error persists.

**Comment by felipeleusin** [comment]
From what I looked this is fixed by the #22 mega refactor PR

**Comment by Mpdreamz** [comment]
Still interesting though, using the published version of editorconfig-visualstudio on 2015 without a problem. 

The mega refactor PR also switched to a managed version (C#) of the editorconfig core library so it should be easier to redistribute.
