### ISSUE TITLE
cleaning large files slow

### ISSUE THREAD

**Issue by Mpdreamz** [editorconfig/editorconfig-visualstudio#41]
and crashes visual studio

**Comment by Mpdreamz** [comment]
when trim_trailing_whitespace is set to true

**Comment by KindDragon** [comment]
What file size?

**Comment by Mpdreamz** [comment]
This is in the unpublished version on the master branch, halfway through a fix locally.

**Comment by robertcoltheart** [comment]
@Mpdreamz I'm not seeing this behavior in master on VS 2015. Do you have an example project and/or setup that you see this failing with?

**Comment by Mpdreamz** [comment]
Hi @robertcoltheart , it happens on huge files with a lot of editor config offenses. 

Example is elastic/elasticsearch-net where the .Generated.cs files have a lot of single trailing spaces not allowed by editorconfig
