### ISSUE TITLE
first word lower

### ISSUE THREAD

**Issue by bluekuen** [editorconfig/editorconfig-visualstudio#63]
Hello,

i want a rule to make the first word in lower of my method/function names.

I have this block of code:

#method names first word lower
dotnet_naming_rule.functions_should_be_camel_case.severity = warning
dotnet_naming_rule.functions_should_be_camel_case.symbols = functions
dotnet_naming_rule.functions_should_be_camel_case.style = function_style

dotnet_naming_symbols.functions.applicable_kinds = method
dotnet_naming_symbols.functions.required_modifiers = *
dotnet_naming_symbols.functions.applicable_accessibilites = *

dotnet_naming_style.function_style.capitalization = camel_case

But it's not working.  What am i doing wrong ? Please help.

**Comment by ffes** [comment]
Your question is about a Microsoft/.NET specific extension to the standard.

See https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference for more information about their settings. It is well documented is my experience.

**Comment by bluekuen** [comment]
yes I#m so sorry.
