### ISSUE TITLE
.EditorConfig - Mark // to do as "Warning"

### ISSUE THREAD

**Issue by DeviZ9** [editorconfig/editorconfig-visualstudio#64]
Hi Dear Developer,
I am looking for a way to mark **// to do** in the code as warning.

Ex: 
void GetInfoFromAPI()
{
// to do - Call Azure DevOps API
}

This should be marked as a "warning". Please suggest me.

**Comment by jedmao** [comment]
This is not within the design goals of EditorConfig.
